### PR TITLE
Mobile-menu-hamburger-function

### PR DESCRIPTION
**Pull request by ehs9nino**
making menu mobile

### CODE REVIEW

**Comment by ehs9nino** [comment]
With the help of my coding partner's, I was able to create a hamburger mobile menu, when we presses the button then we can open a mobile menu options and also we put functionality for closing and we linked the menu's with the different sections of out page.

**Review by zainsadaqat — CHANGES_REQUESTED** [review]
# Hello @ehs9nino 😃 😄 

You're doing a great job on your project. We're proud of you. Good job so far! 
# 👏🏻 👏🏻 👏🏻 

There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
  ✅  Correct use of Github Flow
  ✅  No linter errors

## Required Changes ♻️

**Figma Template Design**
Screen Shot 2022-04-12 at 3 04 42 PM


**Your Design**
Screen Shot 2022-04-12 at 3 05 31 PM

- [ ] You're missing a cross button on the top-left which will close the mobile-menu
- [ ] Mobile menu links are center-aligned but according to the Figma design template. it should be left-aligned. Kindly stick with the required Figma design. 👍🏻 

[Optional]
- [ ] Please write a descriptive pull request which will show what you have done in this pull request.

_Check the comments under the review._




## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding! 👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ehs9nino** [comment]
@zainsadaqat thanks for reviewing this project. And I am going to fix the issues you mentioned above.
 I am little concerned about the hamburger menu closing icons because here I can see it clearly but I don't understand why is it hidden at  your end.
 
Screenshot from 2022-04-12 15-38-52

please check it's working properly.

**Comment by ehs9nino** [comment]
So I have fixed the errors and now we believe this project also meets the Figma design recommendations, 
Here is the more details below 
- We have created a section in which displays only when the hamburger is pressed, we have done it all using java Script DOM manipulations.
-  3 main functions are used in JavaScript file, first one performs actions when we click on hamburger and it open  one container and hides all the main container
- Second is like the same but it's reversed, like when we click on the close button the function perform action and take us back to the main page by hiding the hamburger page.
- Third function in mobile-menu is just directing us to the different sections in the main page, basically it consists of three functions because we have three menu items.

**Comment by zainsadaqat** [comment]
> @zainsadaqat thanks for reviewing this project. And I am going to fix the issues you mentioned above. I am little concerned about the hamburger menu closing icons because here I can see it clearly but I don't understand why is it hidden at your end.
> 
> Screenshot from 2022-04-12 15-38-52
> 
> please check it's working properly.

Hey @ehs9nino 😃 
I pulled the latest changes. It's perfectly left aligned now as per requirement. But the cross button (X) isn't showing up. Although, when I click on the area where the cross button is located is working fine but the problem is, that the cross button isn't visible.

Screen Shot 2022-04-12 at 5 46 04 PM

**Review by OLIPLICHE — APPROVED** [review]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ehs9nino** [comment]
Thanks for the review!

**Pull request merged**
